/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export type OctoWalletArgsStruct = {
  owner: AddressLike;
  entryPoint: AddressLike;
  walletFactory: AddressLike;
  init: AddressLike;
  initCalldata: BytesLike;
};

export type OctoWalletArgsStructOutput = [
  owner: string,
  entryPoint: string,
  walletFactory: string,
  init: string,
  initCalldata: string
] & {
  owner: string;
  entryPoint: string;
  walletFactory: string;
  init: string;
  initCalldata: string;
};

export declare namespace IDiamond {
  export type FacetCutStruct = {
    facetAddress: AddressLike;
    action: BigNumberish;
    functionSelectors: BytesLike[];
  };

  export type FacetCutStructOutput = [
    facetAddress: string,
    action: bigint,
    functionSelectors: string[]
  ] & { facetAddress: string; action: bigint; functionSelectors: string[] };
}

export interface OctoWalletFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createWallet"
      | "getCoreFacetCuts"
      | "getOctoWalletArgs"
      | "getWalletAddress"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "WalletCreated"): EventFragment;

  encodeFunctionData(
    functionFragment: "createWallet",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCoreFacetCuts",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getOctoWalletArgs",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getWalletAddress",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "createWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCoreFacetCuts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOctoWalletArgs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWalletAddress",
    data: BytesLike
  ): Result;
}

export namespace WalletCreatedEvent {
  export type InputTuple = [
    wallet: AddressLike,
    owner: AddressLike,
    salt: BigNumberish
  ];
  export type OutputTuple = [wallet: string, owner: string, salt: bigint];
  export interface OutputObject {
    wallet: string;
    owner: string;
    salt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface OctoWalletFactory extends BaseContract {
  connect(runner?: ContractRunner | null): OctoWalletFactory;
  waitForDeployment(): Promise<this>;

  interface: OctoWalletFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createWallet: TypedContractMethod<
    [walletOwner: AddressLike, salt: BigNumberish],
    [string],
    "nonpayable"
  >;

  getCoreFacetCuts: TypedContractMethod<
    [],
    [IDiamond.FacetCutStructOutput[]],
    "view"
  >;

  getOctoWalletArgs: TypedContractMethod<
    [walletOwner: AddressLike],
    [OctoWalletArgsStructOutput],
    "view"
  >;

  getWalletAddress: TypedContractMethod<
    [walletOwner: AddressLike, salt: BigNumberish],
    [string],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createWallet"
  ): TypedContractMethod<
    [walletOwner: AddressLike, salt: BigNumberish],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getCoreFacetCuts"
  ): TypedContractMethod<[], [IDiamond.FacetCutStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "getOctoWalletArgs"
  ): TypedContractMethod<
    [walletOwner: AddressLike],
    [OctoWalletArgsStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getWalletAddress"
  ): TypedContractMethod<
    [walletOwner: AddressLike, salt: BigNumberish],
    [string],
    "view"
  >;

  getEvent(
    key: "WalletCreated"
  ): TypedContractEvent<
    WalletCreatedEvent.InputTuple,
    WalletCreatedEvent.OutputTuple,
    WalletCreatedEvent.OutputObject
  >;

  filters: {
    "WalletCreated(address,address,uint256)": TypedContractEvent<
      WalletCreatedEvent.InputTuple,
      WalletCreatedEvent.OutputTuple,
      WalletCreatedEvent.OutputObject
    >;
    WalletCreated: TypedContractEvent<
      WalletCreatedEvent.InputTuple,
      WalletCreatedEvent.OutputTuple,
      WalletCreatedEvent.OutputObject
    >;
  };
}
