/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ViewFunctionInit,
  ViewFunctionInitInterface,
} from "../ViewFunctionInit";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes4[]",
        name: "viewFunctionSelectors",
        type: "bytes4[]",
      },
    ],
    name: "init",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ViewFunctionInit__factory {
  static readonly abi = _abi;
  static createInterface(): ViewFunctionInitInterface {
    return new Interface(_abi) as ViewFunctionInitInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ViewFunctionInit {
    return new Contract(address, _abi, runner) as unknown as ViewFunctionInit;
  }
}
